name: notify-feishu
on:
  workflow_run:      # 由主 workflow 完成后触发
    workflows: ["Sync Feishu Table to GitHub"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 转发到服务器
        run: |
          curl -X POST ${{ secrets.SERVER_HOST }}:5000/DTOL-Dialogue-Data/notify \
            -H "Content-Type: application/json" \
            -d '{
                  "status": "${{ github.event.workflow_run.conclusion }}",
                  "actor": "${{ github.event.workflow_run.triggering_actor.login }}",
                  "run_url": "${{ github.event.workflow_run.html_url }}"
                }'
