name: Sync Feishu Table to GitHub

on:
  # 每天凌晨 3 点自动跑一次（可选）
  schedule:
    - cron: '0 3 * * *'

  # 手动触发
  workflow_dispatch:

  # 飞书 Webhook 触发（repository_dispatch）
  repository_dispatch:
    types: [feishu_update]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库（带完整历史，避免冲突）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2. 安装 Python 与依赖
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flatbuffers
          pip install requests

      - name: Install flatc
        run: |
          curl -L https://github.com/google/flatbuffers/releases/download/v23.5.26/Linux.flatc.binary.g++-10.zip -o flatc.zip
          unzip flatc.zip && chmod +x flatc && sudo mv flatc /usr/local/bin/

      - name: Generate flatbuffers Python bindings
        run: |
          flatc --python tools/dialog.fbs  # 生成 Dialog/*.py 供 export_dialog.py import
          # 如果 C# 也要用，可再跑 flatc --csharp dialog.fbs

      # 先把远端最新代码拉下来
      - run: git pull --rebase origin main

      - name: Pull & convert
        env:
          FEISHU_APP_ID:     ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_APP_TOKEN:  ${{ secrets.FEISHU_APP_TOKEN }}
        run: python tools/pull_feishu.py

      # 官方动作：add / commit / push（自动 rebase）
      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'feishu_tables/*'
          message: 'Auto sync all tables & views'
