name: Sync Feishu Table to GitHub

on:
  # 每天凌晨 3 点自动跑一次（可选）
  schedule:
    - cron: '0 3 * * *'

  # 手动触发
  workflow_dispatch:

  # 飞书 Webhook 触发（repository_dispatch）
  repository_dispatch:
    types: [feishu_update]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉仓库源码（含脚本）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 装 Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. 装依赖
      - name: Install deps
        run: |
          pip install requests flatbuffers

      # 4. 拉飞书表 → 生成 .bytes
      - name: Pull & convert
        env:
          FEISHU_APP_ID:     ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_APP_TOKEN:  ${{ secrets.FEISHU_APP_TOKEN }}
        run: |
          python tools/pull_feishu.py

      # 5. 打包成 zip
      - name: Zip feishu_tables
        run: |
          cd feishu_tables
          zip -r ../feishu_tables.zip ./*

      # 5.1 生成新的 remote_version.txt (UTC 时间戳)
      - name: Generate version
        run: |
          echo "$(date -u +%Y%m%d%H%M%S)" > remote_version.txt
          
      # 6. 把最新 .bytes 与 zip 提交回仓库
      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            feishu_tables/**/*.bytes
            feishu_tables.zip
            remote_version.txt
          message: 'chore: auto-sync Feishu → .bytes & zip'
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          
      # 7. 安装 ssh-client 并写入私钥
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # 8. 上传 zip + version.txt 到服务器目录
      - name: Upload to server
        run: |
          rsync -avz -e "ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_ed25519" \
            feishu_tables.zip remote_version.txt \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/static/feishu/

