name: Sync Feishu Table to GitHub

on:
  # 每天凌晨 3 点自动跑一次（可选）
  schedule:
    - cron: '0 3 * * *'

  # 手动触发
  workflow_dispatch:

  # 飞书 Webhook 触发（repository_dispatch）
  repository_dispatch:
    types: [feishu_update]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: pip install requests

    - name: Pull data from Feishu
      env:
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        FEISHU_APP_TOKEN: ${{ secrets.FEISHU_APP_TOKEN }}
        FEISHU_TABLE_ID: ${{ secrets.FEISHU_TABLE_ID }}
      run: python tools/pull_feishu.py

    - name: Commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git pull --rebase origin main        # 1. 先同步远程最新
        git add feishu_data.json
        git diff --cached --quiet || git commit -m "Auto sync from Feishu table"
        git push                             # 2. 再推送
