name: Sync Feishu Table to GitHub

on:
  # 每天凌晨 3 点自动跑一次（可选）
  schedule:
    - cron: '0 3 * * *'

  # 手动触发
  workflow_dispatch:

  # 飞书 Webhook 触发（repository_dispatch）
  repository_dispatch:
    types: [feishu_update]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库（带完整历史，避免冲突）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2. 安装 Python 与依赖
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      # 3. 拉取飞书数据
      - name: Pull data from Feishu
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_APP_TOKEN: ${{ secrets.FEISHU_APP_TOKEN }}
          FEISHU_TABLE_ID: ${{ secrets.FEISHU_TABLE_ID }}
        run: python scripts/pull_feishu.py

      # 4. 官方动作：add / commit / push（自动 rebase）
      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'feishu_data.json'
          message: 'Auto sync from Feishu table'
